// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBmkiPBeNTWNt0VAPBIRZ46N7zlV0Agc',
    appId: '1:297023016581:web:91c7d1e4eb64dbe49823ec',
    messagingSenderId: '297023016581',
    projectId: 'tlob-jewellery',
    authDomain: 'tlob-jewellery.firebaseapp.com',
    storageBucket: 'tlob-jewellery.firebasestorage.app',
    measurementId: 'G-W13B8XSHJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARyoBcC29I9Xnlg9SYW8DJ8x7KKMb9M2E',
    appId: '1:297023016581:android:27a69465c3fa23bf9823ec',
    messagingSenderId: '297023016581',
    projectId: 'tlob-jewellery',
    storageBucket: 'tlob-jewellery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNwytD4nki6596l7FaOGE0SvCxCnxvzs',
    appId: '1:297023016581:ios:f1da718f0da2dff79823ec',
    messagingSenderId: '297023016581',
    projectId: 'tlob-jewellery',
    storageBucket: 'tlob-jewellery.firebasestorage.app',
    iosBundleId: 'com.example.tlobJewelleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNwytD4nki6596l7FaOGE0SvCxCnxvzs',
    appId: '1:297023016581:ios:f1da718f0da2dff79823ec',
    messagingSenderId: '297023016581',
    projectId: 'tlob-jewellery',
    storageBucket: 'tlob-jewellery.firebasestorage.app',
    iosBundleId: 'com.example.tlobJewelleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBBmkiPBeNTWNt0VAPBIRZ46N7zlV0Agc',
    appId: '1:297023016581:web:b7e0105cb37b2acd9823ec',
    messagingSenderId: '297023016581',
    projectId: 'tlob-jewellery',
    authDomain: 'tlob-jewellery.firebaseapp.com',
    storageBucket: 'tlob-jewellery.firebasestorage.app',
    measurementId: 'G-GVXRBK95M4',
  );
}
